name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare PNPM
        run: npm install -g pnpm
      - name: Install dependencies with PNPM
        run: pnpm install
      - name: Build website
        run: pnpm run build
